apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: 
      terminationGracePeriodSeconds: 60
      containers:
      - name: hello-pod
        image: markusbcit/web-app:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
