
---
- name: Create user 
  hosts: all
  tasks:
    - name: Create user bum
      become: true
      user:
        name: bun
        state: present
        shell: /bin/bash
        create_home: yes
        # groups: sudo

- name: Install packages
  hosts: all
  tasks:
    - name: Install unzip 
      become: true
      apt:
        name: unzip
        state: present

    - name: Install bun
      become: true
      shell:
        cmd: "curl -fsSL https://bun.sh/install | bash"
        # chdir: "/home/bun"

    - name: Add lines to .bashrc for user 'bun' # This is only here because I couldn't install as bun user.
      become: true
      lineinfile:
        dest: "/home/bun/.bashrc"
        line: |
          # bun
          export BUN_INSTALL="$HOME/.bun"
          export PATH=$BUN_INSTALL/bin:$PATH

    - name: copy .bun to /home/bun
      become: true
      shell: 'cp -r /root/.bun /home/bun/' # https://abdusfauzi.com/2023/11/03/how-to-install-bun-sh-for-global-ubuntu-users-other-than-root/

    - name: Install Caddy
      become: true
      shell: |
        sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https curl
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
        sudo apt update
        sudo apt install caddy

- name: Copy files
  hosts: all
  tasks:
    - name: Copy content
      become: true
      ansible.builtin.copy:
        src: /home/markus/4640/as2/ansible/bun-htmx-4640
        dest: /home/bun/

    - name: Copy service file
      become: true
      ansible.builtin.copy:
        src: /home/markus/4640/as2/ansible/bun-4640-project.service
        dest: /etc/systemd/system/
    
    - name: Copy service file 
      become: true
      ansible.builtin.copy:
        src: /home/markus/4640/as2/ansible/Caddyfile
        dest: /etc/caddy/Caddyfile


- name: Install node_modules 
  hosts: all
  tasks:
    - name: Install node_modules 
      become: true 
      shell: 
        cmd: "/home/bun/.bun/bin/bun i"
        chdir: "/home/bun/bun-htmx-4640"

- name: Configure services
  hosts: all
  tasks:
    - name: Restart caddy
      become: true
      ansible.builtin.service:
        name: caddy
        state: restarted

    - name: Start bun-4640-project
      become: true
      ansible.builtin.service:
        name: bun-4640-project
        state: started
