apiVersion: v1
kind: Pod
metadata:
  name: business-app
spec:
  volumes:
  - name: logs-volume    
    emptyDir: {}  
  containers:  
  - image: nginx    
    name: nginx    
    volumeMounts:    
    - mountPath: /var/logs      
      name: logs-volume
  - image: alpine
    name: app
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 60; done;"]
    volumeMounts:
      - mountPath: "/mnt/data"
        name: logs-volume