image: python:3.11-slim

stages:
  - build
  - lint
  - test
  - zip
cache:
  paths:
    - venv/
    - .cache/pip


build:
  stage: build
  script:
    - apt-get update && apt-get install -y python3 python3-venv python3-pip
    - rm -rf venv  
    - python3 -m venv venv  
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install --upgrade flask
    - pip install pylint
    - pip install pytest


lint:
  stage: lint
  script:
    - source venv/bin/activate
    - python3 -m pylint --fail-under 5 *.py

test_and_coverage:
  stage: test
  script:
    - rm -f test-reports/*.xml || true
    - rm -f api-test-reports/*.xml || true
    - for testfile in test*.py; do 
        . venv/bin/activate; 
        which python; 
        which coverage; 
        coverage run --omit "*/site-packages/*,*/dist-packages/*" "$testfile"; 
        coverage xml -o "test-reports/$(basename "$testfile" .py).xml"; 
      done
    - coverage report
    - coverage xml
  artifacts:
    when: always
    reports:
      junit: 
        - test-reports/*.xml
        - api-test-reports/*.xml
    paths:
      - api-test-reports/*.xml
      - test-reports/*.xml

zip:
  stage: zip
  script:
    - ls
  artifacts:
    paths:
      - "*.py"

